language: java
dist: xenial
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11

after_success:
  - mvn clean test jacoco:report coveralls:report

sudo: false

notifications:
  email:
    - iluwatar@gmail.com
    - hemant.bothra15@gmail.com
